name: Binaries
on:
  push:
    branches: [ master, next ]
  pull_request:
    branches: [ master, next ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: catalinii/minisatip-build-image:latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: '0'
    - name: Build x64
      run: |
       ./configure --enable-static CXX="clang++ -static" --disable-netcv
       make DDCI=1
       zip -9 -r /minisatip_x64.zip minisatip html

    - name: Build ARM
      run: |
       make clean
       ./configure --disable-netcv --enable-static --host=arm-linux-gnueabihf CXX="clang++ -target arm-linux-gnueabihf -static"
       make
       zip -9 -r /minisatip_arm.zip minisatip html

    - name: Build MIPS
      run: |
       make clean
       ./configure --disable-netcv --enable-static --host=mipsel-linux-gnu CXX="zig c++ -target mipsel-linux"
       make EXTRA_CFLAGS="-I/sysroot/mipsel/include -L/sysroot/mipsel/lib"
       zip -9 -r /minisatip_mips.zip minisatip html

    - name: Archive built binaries
      uses: actions/upload-artifact@v4
      with:
        name: minisatip
        path: |
          /minisatip_x64.zip
          /minisatip_arm.zip
          /minisatip_axe.zip
          /minisatip_mips.zip

    - name: Bump version and push tag/create release point
      uses: anothrNick/github-tag-action@1.35.0
      if: ${{ github.event_name == 'push' && github.repository_owner == 'catalinii' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: patch
      id: bump_version
    - name: Upload binary to release
      uses: svenstaro/upload-release-action@v2
      if: ${{ github.event_name == 'push' && github.repository_owner == 'catalinii' }}
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: /minisatip*zip
        file_glob: true
        tag: ${{ steps.bump_version.outputs.new_tag }}
        overwrite: true
