name: Binaries
on:
  push:
    branches: [ master, next ]
  pull_request:
    branches: [ master, next ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: catalinii/minisatip-build-image:latest
    env:
      PR: ${{ github.event.number }}
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: '0'
    - uses: mlugg/setup-zig@v2
      with:
        version: 0.13.0
    - name: Mark workspace as safe for git usage
      # actions/checkout normally handles this, but not when using a container
      run: git config --system --add safe.directory "$GITHUB_WORKSPACE"

      # We must bump the version before we build so the version number becomes correct.
    - name: Bump version and push tag/create release point
      id: bump_version
      uses: anothrNick/github-tag-action@1.35.0
      if: ${{ github.event_name == 'push' && github.repository_owner == 'catalinii' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: patch

    - name: Build x64
      run: |
        ./configure --disable-netcv --enable-static CXX="clang++ -static"
        make DDCI=1
        file minisatip
        zip -9 -r /minisatip_x64.zip minisatip html

    - name: Build ARM
      run: |
        make clean
        ./configure --disable-netcv --enable-static --host=arm-linux-gnueabihf CXX="clang++ -target arm-linux-gnueabihf -static"
        make
        file minisatip
        zip -9 -r /minisatip_arm.zip minisatip html

    - name: Build MIPS
      run: |
        make clean
        ./configure --disable-netcv --enable-static --host=mipsel-linux-gnu CXX="zig c++ -target mipsel-linux-gnueabihf -I/usr/mipsel-linux-gnueabihf/include/ -L/usr/mipsel-linux-gnueabihf/lib/"
        make
        file minisatip
        zip -9 -r /minisatip_mips.zip minisatip html

    - name: Build MIPS (musl)
      run: |
        make clean
        ./configure --disable-netcv --enable-static --host=mipsel-linux-gnu CXX="zig c++ -target mipsel-linux-musl -I/usr/mipsel-linux-gnueabihf/include/ -L/usr/mipsel-linux-gnueabihf/lib/"
        make
        file minisatip
        zip -9 -r /minisatip_mips_musl.zip minisatip html

    - name: Archive built binaries
      uses: actions/upload-artifact@v4
      with:
        name: minisatip
        path: |
          /minisatip_x64.zip
          /minisatip_arm.zip
          /minisatip_axe.zip
          /minisatip_mips.zip
          /minisatip_mips_musl.zip

    - name: Upload binary to release
      uses: svenstaro/upload-release-action@v2
      if: ${{ github.event_name == 'push' && github.repository_owner == 'catalinii' }}
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: /minisatip*zip
        file_glob: true
        tag: ${{ steps.bump_version.outputs.new_tag }}
        overwrite: true
