name: Coverity

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  coverity:
    runs-on: ubuntu-latest
    container: catalinii/minisatip-build-image:latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure
        run: ./configure --with-mcli=/vdr-plugin-mcli/

      - name: Download Coverity Build Tool
        run: |
          wget -q https://scan.coverity.com/download/cxx/linux64 --post-data "token=$TOKEN&project=MINISATIP" -O cov-analysis-linux64.tar.gz
          mkdir cov-analysis-linux64
          tar xzf cov-analysis-linux64.tar.gz --strip 1 -C cov-analysis-linux64
        env:
          TOKEN: ${{ secrets.COVERITY_SCAN_TOKEN }}

      - name: Build with cov-build
        run: |
          export PATH=`pwd`/cov-analysis-linux64/bin:$PATH
          cov-build --dir cov-int make

      - name: Submit the result to Coverity Scan
        run: |
          tar czvf MINISATIP.tgz cov-int
          curl \
            --form project=MINISATIP \
            --form token=$TOKEN \
            --form email='reply+AB6SAEPNLEJSCE2WJ37GDNF6TC2NXEVBNHHDIEHQTY@reply.github.com' \
            --form file=@MINISATIP.tgz \
            --form version=trunk \
            --form description="`./minisatip -v`" \
            https://scan.coverity.com/builds?project=MINISATIP
        env:
          TOKEN: ${{ secrets.COVERITY_SCAN_TOKEN }}
