name: Debian packages
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-24.04
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: '0'
    - name: Configure working directory as git safe.directory
      run: |
        git config --global --add safe.directory /__w/minisatip/minisatip

    - name: Install build dependencies
      run: |
        sudo DEBIAN_FRONTEND=noninteractive apt-get -y install build-essential dpkg-dev libdvbcsa-dev libssl-dev debhelper-compat vdr-dev cmake

    - name: Build Debian package
      run: |
        mkdir -p build
        rsync -a --exclude=build . build
        cd build
        ./debian/gen_changelog unstable $(git describe --tags | sed 's/v//') $(git rev-parse --short HEAD) > debian/changelog
        dpkg-buildpackage -b -us -uc

    - name: Archive the built package
      uses: actions/upload-artifact@v3
      with:
        name: minisatip-deb
        path: '*.deb'
